services:
    frontend:
        build: ./frontend
        ports:
        - "3000:3000"
        env_file:
        - ./.env.docker
        networks:
        - app_network
        depends_on:
        - backend

    backend:
        build: ./backend
        command: "poetry run uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"
        volumes:
            - ./:/code/
        ports:
            - 8000:8000
        depends_on:
            - db
        env_file:
            - "./.env.docker"
        environment:
        - PYTHONDONTWRITEBYTECODE=1
    
    db:
        image: mongo:latest
        volumes:
            - "mongodb_data:/data/db"
        ports:
            - "27017:27017"
        networks:
            -app_network
    
    networks:
        app_network:
            driver: bridge

volumes:
    mongodb_data: