name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: backend
            dockerfile: backend/Dockerfile
            context: backend
          - name: frontend
            dockerfile: frontend/Dockerfile
            context: frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: mrgreen1337
        password: H1988s1992S1994i2003_

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.dockerfile }}
        push: true
        tags: mrgreen1337/${{ matrix.name }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max